# Generated by Django 3.0.7 on 2021-03-31 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='not provided', max_length=70)),
                ('category', models.CharField(max_length=70)),
                ('title', models.CharField(max_length=70)),
                ('content', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=70)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
